Modify user
greenbone/python-gvm pull request #347
Opened 2020-11-25 13:53 UTC by ArnoStiefvater

**What**:

Modify user now only takes an ID for identifying the user which is to be modified.
The name parameter is now the new name and not an identifier anymore.
The comment, auth_source and group_ids parameters got added. Now its possible to change those fields too. auth_source has to be used explicitly if not the default Source allowed for authentication for the user is to be used.

**Why**:

To be able to set the appropriate fields.

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/python-gvm/blob/master/CHANGELOG.md) Entry
- [ ] Documentation

2020-11-25 13:58 UTC, y0urself commented
As mentioned before: I think this should be in an earlier version of gmp ...?!

2020-11-25 14:09 UTC, ArnoStiefvater commented
> As mentioned before: I think this should be in an earlier version of gmp ...?!

But this change completely breaks the API. For example it is not possible to identifying a user bey name anymore. Its not only adding stuff. I can modify the 208 function to include the comment, user_auth and group_ids params, but the name change breaks the API.

2020-11-26 11:02 UTC, y0urself requested changes

2020-11-26 11:02 UTC, y0urself commented on gvm/protocols/gmpv7/gmpv7.py
> +        group_ids: Optional[List[str]] = None,
```suggestion
        group_ids: Optional[List[str]] = None
```

2020-11-26 11:42 UTC, y0urself commented
you  may add a test for the new Enum `UserAuthType` ? In `testtypes`?

2020-11-26 16:08 UTC, nichtsfrei approved these changes

2020-11-26 16:09 UTC, y0urself approved these changes

2020-11-26 16:09 UTC, merged