Add allow_simult_ips_same_host param for targets
greenbone/python-gvm pull request #380
Opened 2021-01-18 11:18 UTC by timopollmeier

**What**:
The create_target and modify_target commands now have an optional
parameter to set whether scanning multiple IPs per host simultaneously
is allowed.
The tests for the commands are updated accordingly.

**Why**:
To make the new option usable in python-gvm.

**How**:
Tested by running a program that uses the two commands, including the
new option.

**Checklist**:

- [x] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/python-gvm/blob/master/CHANGELOG.md) Entry
- [ ] Documentation

2021-01-19 08:45 UTC, bjoernricks reviewed
I am not 100% sure about the variable name `allow_simult_ips_same_host`. But `allow_simultaneous_ips_same_host` gets a bit long. @y0urself can decide about that.

2021-01-19 09:08 UTC, y0urself commented
> I am not 100% sure about the variable name `allow_simult_ips_same_host`. But `allow_simultaneous_ips_same_host` gets a bit long. @y0urself can decide about that.

Yeah would agree.
I would do something like `multiple_host_ips`. Any curiosities can be solved by the comment and documentation ...

2021-01-20 10:58 UTC, bjoernricks commented
What about `allow_multiple_ips_per_host`?

2021-01-20 11:09 UTC, y0urself commented
I don't think that `allow` needs to be mentioned here ... as its a boolean that can be `True` or `False` it might be enough to make it `multiple_ips_per_host`. For me allow refers more to Yes or No, not False or True.

2021-01-20 11:17 UTC, bjoernricks commented
You are right. I am fine with `multiple_ips_per_host`. @timopollmeier do you agree?

2021-01-20 13:38 UTC, y0urself requested changes

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +            allow_simult_ips_same_host: Whether to scan multiple IPs of the
```suggestion
            multiple_ips_per_host: Whether to scan multiple IPs of the
```

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +        allow_simult_ips_same_host: Optional[bool] = None,
```suggestion
        multiple_ips_per_host: Optional[bool] = None,
```

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +        if allow_simult_ips_same_host is not None:
```suggestion
        if multiple_ips_per_host is not None:
```

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +                _to_bool(allow_simult_ips_same_host),
```suggestion
                _to_bool(multiple_ips_per_host),
```

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +        allow_simult_ips_same_host: Optional[bool] = None,
```suggestion
        multiple_ips_per_host: Optional[bool] = None,
```

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +            allow_simult_ips_same_host: Whether to scan multiple IPs of the
```suggestion
            multiple_ips_per_host: Whether to scan multiple IPs of the
```

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +        if allow_simult_ips_same_host is not None:
```suggestion
        if multiple_ips_per_host is not None:
```

2021-01-20 13:38 UTC, y0urself commented on gvm/protocols/gmpv214/gmpv214.py
> +                _to_bool(allow_simult_ips_same_host),
```suggestion
                _to_bool(multiple_ips_per_host),
```

2021-01-20 13:38 UTC, y0urself commented on tests/protocols/gmpv214/testcmds/test_create_target.py
> +    def test_create_target_with_allow_simult_ips_same_host(self):
```suggestion
    def test_create_target_with_multiple_ips_per_host(self):
```

2021-01-20 13:38 UTC, y0urself commented on tests/protocols/gmpv214/testcmds/test_create_target.py
> +            allow_simult_ips_same_host=True
```suggestion
            multiple_ips_per_host=True
```

2021-01-20 13:38 UTC, y0urself commented on tests/protocols/gmpv214/testcmds/test_create_target.py
> +            allow_simult_ips_same_host=False
```suggestion
            multiple_ips_per_host=False
```

2021-01-20 13:38 UTC, y0urself commented on tests/protocols/gmpv214/testcmds/test_modify_target.py
> +    def test_modify_target_with_allow_simult_ips_same_host(self):
```suggestion
    def test_modify_target_with_multiple_ips_per_host(self):
```

2021-01-20 13:38 UTC, y0urself commented on tests/protocols/gmpv214/testcmds/test_modify_target.py
> +        self.gmp.modify_target(target_id='t1', allow_simult_ips_same_host=False)
```suggestion
        self.gmp.modify_target(target_id='t1', multiple_ips_per_host=False)
```

2021-01-20 13:38 UTC, y0urself commented on tests/protocols/gmpv214/testcmds/test_modify_target.py
> +        self.gmp.modify_target(target_id='t1', allow_simult_ips_same_host=True)
```suggestion
        self.gmp.modify_target(target_id='t1', multiple_ips_per_host=True)
```

2021-01-22 15:06 UTC, y0urself requested changes

2021-01-22 15:06 UTC, y0urself commented on tests/protocols/gmpv214/testcmds/__init__.py
> +# Copyright (C) 2021 Greenbone Networks GmbH
```suggestion
# Copyright (C) 2020-2021 Greenbone Networks GmbH
```

2021-01-22 15:06 UTC, y0urself approved these changes

2021-01-22 15:22 UTC, merged